import { expect, test } from '@playwright/test'

test('creates a task, opens Monaco, and completes a mock execution', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await expect(page.getByText('Workflow Definitions')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Add Task' })).toBeVisible()

  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  await expect(page.getByRole('heading', { name: 'http_task' })).toBeVisible()

  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await expect(page.locator('.monaco-editor')).toHaveCount(1, { timeout: 10_000 })

  await page.getByRole('button', { name: 'Execute', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Execute workflow' })).toBeVisible()
  await page.getByRole('button', { name: 'Start execution', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Execution completed', exact: true })).toBeVisible({ timeout: 10_000 })
  await expect(page.getByText('workflow.completed', { exact: false })).toBeVisible()
})

test('adds a task from a node plus connector', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.locator('.loop-node .node-add-connector').click()
  await expect(page.getByText('AGENTIC ORCHESTRATION')).toBeVisible()
  await page.locator('.quick-add-menu button').filter({ hasText: /^HTTP$/ }).click()
  await expect(page.locator('.quick-add-menu')).toHaveCount(0)
  await expect(page.locator('.canvas-ribbon')).toContainText('13 connections')
  await expect(page.locator('.task-node').filter({ hasText: 'http_task' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Add task inside Do While' }).click()
  await page.locator('.quick-add-menu button').filter({ hasText: /^HTTP$/ }).click()
  await expect(page.locator('.loop-node .group-slot')).toContainText('http_task')
  await page.getByRole('button', { name: 'Delete nested task http_task' }).click()
  await expect(page.locator('.loop-node .group-slot').filter({ hasText: 'http_task' })).toHaveCount(0)
})

test('deletes a task from its node close button', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  const task = page.locator('.task-node').filter({ hasText: 'http_task' })
  await expect(task).toHaveCount(1)
  await task.locator('.node-remove').click()
  await expect(task).toHaveCount(0)
})

test('configures a Worker Task from the Orkes task reference fields', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /Worker Task \(Simple\)/ }).first().click()
  await expect(page.getByText('Worker task options')).toBeVisible()
  await page.locator('input[placeholder="sayHello"]').fill('sayHello')
  await page.locator('.worker-section input[type="checkbox"]').nth(0).check()
  await expect(page.getByText('TTL (seconds)')).toBeVisible()
  await page.locator('.worker-section input[placeholder="${workflow.input.jobId}"]').fill('${workflow.input.firstName}')
  await page.locator('.worker-section input[type="checkbox"]').nth(1).check()
  await expect(page.getByText('Input schema')).toBeVisible()
})

test('shows the Orkes operator catalog in Add Task', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await expect(page.getByRole('button', { name: /Dynamic Fork/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Exclusive Join/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Get Workflow/ })).toBeVisible()
})

test('shows dedicated polling controls for an HTTP Poll task', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /HTTP Poll Task/ }).first().click()
  await expect(page.getByText('Polling', { exact: true })).toBeVisible()
  await expect(page.getByText('Poll interval (sec)', { exact: true })).toBeVisible()
  await expect(page.getByText('Poll condition', { exact: true })).toBeVisible()
})

test('shows dedicated official forms for advanced task types', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /Get Signed JWT/ }).first().click()
  await expect(page.getByText('Private key ID', { exact: true })).toBeVisible()
  await expect(page.getByText('Algorithm', { exact: true })).toBeVisible()
})

test('shows canonical fields for Kafka, gRPC, rules, databases and secrets', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /Kafka Publish/ }).first().click()
  await expect(page.getByText('Bootstrap server', { exact: true })).toBeVisible()
  await expect(page.getByText('Key serializer', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /gRPC Task/ }).first().click()
  await expect(page.getByText('Method type', { exact: true })).toBeVisible()
  await expect(page.getByText('Use SSL', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /Business Rule Task/ }).first().click()
  await expect(page.getByText('Rule file location', { exact: true })).toBeVisible()
  await expect(page.getByText('Input columns (JSON object)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /JDBC Task/ }).first().click()
  await expect(page.getByText('Statement type', { exact: true })).toBeVisible()
  await expect(page.getByText('Query parameters (JSON array)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /Update Secret/ }).first().click()
  await expect(page.getByText('Secret key', { exact: true })).toBeVisible()
  await expect(page.getByText('Secret value', { exact: true })).toBeVisible()
})

test('shows task-specific LLM and retrieval fields', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /LLM Chat Complete/ }).first().click()
  await expect(page.getByText('LLM provider', { exact: true })).toBeVisible()
  await expect(page.getByText('Messages (JSON array)', { exact: true })).toBeVisible()
  await expect(page.getByText('Max tokens', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /LLM Search Index/ }).first().click()
  await expect(page.getByText('Vector database', { exact: true })).toBeVisible()
  await expect(page.getByText('Query', { exact: true })).toBeVisible()
  await expect(page.getByText('Max results', { exact: true })).toBeVisible()
})

test('undo and redo restore task nodes together with their connections', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByTestId('rf__node-submit-job').click()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  await expect(page.locator('.canvas-ribbon')).toContainText('13 connections')
  const newTask = page.locator('.react-flow__node').filter({ hasText: 'http_task' }).first()
  await expect(newTask).toHaveCount(1)
  const pollLoop = page.getByTestId('rf__node-poll-loop')
  const yPosition = async (locator: typeof newTask) => (await locator.getAttribute('style'))?.match(/translate\([^,]+,\s*([^)]*)\)/)?.[1]
  expect(await yPosition(newTask)).toBe(await yPosition(pollLoop))

  await page.getByRole('button', { name: /Undo/ }).click()
  await expect(page.locator('.task-node').filter({ hasText: 'http_task' })).toHaveCount(0)
  await expect(page.locator('.canvas-ribbon')).toContainText('12 connections')

  await page.getByRole('button', { name: /Redo/ }).click()
  await expect(page.locator('.task-node').filter({ hasText: 'http_task' })).toHaveCount(1)
  await expect(page.locator('.canvas-ribbon')).toContainText('13 connections')
})

test('copies, pastes, and duplicates a node with a conflict-safe reference', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  const source = page.getByTestId('rf__node-submit-job')
  await source.click()
  await page.keyboard.press('Control+c')
  await page.keyboard.press('Control+v')
  await expect(page.locator('.task-node').filter({ hasText: 'submit_job_2' })).toHaveCount(1)

  await source.click({ button: 'right' })
  await expect(page.getByRole('button', { name: 'Copy node' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'View JSON' })).toBeVisible()
  await page.getByRole('button', { name: 'View JSON' }).click()
  await expect(page.getByRole('button', { name: 'Code', exact: true })).toHaveClass(/active/)
})

test('pauses, resumes, and terminates a running execution', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Execute', exact: true }).click()
  await page.getByRole('button', { name: 'Start execution', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible({ timeout: 2_000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflow is paused' })).toBeVisible()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Terminate', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Terminate', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Execution terminated' })).toBeVisible()
})

test('supports the workflow builder entry options from the definitions list', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/workflows')
  await expect(page.getByRole('heading', { name: 'Workflow Definitions' })).toBeVisible()
  await page.getByRole('button', { name: /New workflow/ }).click()
  await expect(page.getByText('Create blank', { exact: true })).toBeVisible()
  await expect(page.getByText('Use template', { exact: true })).toBeVisible()
  await expect(page.getByText('Import JSON', { exact: true })).toBeVisible()
  await expect(page.getByText('Generate with AI', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Create blank/ }).click()
  await expect(page.getByText('new_workflow', { exact: true })).toBeVisible()
  await expect(page.locator('.canvas-ribbon')).toContainText('0 tasks')
})

test('navigates the supporting Conductor platform screens from the sidebar', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Queue Monitor', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Queue Monitor', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Event Monitor', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Event Monitor', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Task', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Task Definitions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Event Handler', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Event Handlers', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Scheduler', exact: true }).last().click()
  await expect(page.getByRole('heading', { name: 'Scheduler Definitions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Schemas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Schemas', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'APIs', exact: true }).click()
  await page.getByRole('button', { name: 'Services', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'API Reference', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Agents', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Agent Executions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Access Control' }).click()
  await page.getByRole('button', { name: 'Users', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Users', exact: true })).toBeVisible()
})

test('runs a workflow from the platform Run Workflow screen', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/runWorkflow')
  await expect(page.getByRole('heading', { name: 'Run Workflow', exact: true })).toBeVisible()
  await page.getByLabel('Input params (JSON)').fill('{"source":"e2e"}')
  await page.getByLabel('Execution name').fill('platform-run-e2e')
  await page.getByRole('button', { name: 'Run workflow', exact: true }).click()
  await expect(page.getByText('Execution started', { exact: true })).toBeVisible()
  await expect(page.getByText('platform-run-e2e', { exact: false })).toBeVisible()
})

test('persists saved workflows and exposes definition list actions', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.goto('/workflows')
  await expect(page.getByText('api_polling_workflow', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Actions for api_polling_workflow', exact: true }).click()
  page.once('dialog', (dialog) => dialog.accept('api_polling_copy'))
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
  await expect(page.getByText('api_polling_copy', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Actions for api_polling_copy', exact: true }).click()
  await page.getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(page.locator('.workflow-row').filter({ hasText: 'api_polling_copy' })).toContainText('ARCHIVED')
})

test('deletes a saved workflow from the builder header', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflow Definitions' })).toBeVisible()
  await expect(page.getByText('api_polling_workflow', { exact: true })).not.toBeVisible()
})
