import { expect, test } from '@playwright/test'

test('creates a task, opens Monaco, and completes a mock execution', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await expect(page.getByText('Workflow Definitions')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Add Task' })).toBeVisible()

  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  await expect(page.getByRole('heading', { name: 'http_task' })).toBeVisible()

  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await expect(page.locator('.monaco-editor')).toHaveCount(1, { timeout: 10_000 })

  await page.getByRole('button', { name: 'Execute', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Execute workflow' })).toBeVisible()
  await page.getByRole('button', { name: 'Start execution', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Execution completed', exact: true })).toBeVisible({ timeout: 10_000 })
  await expect(page.getByText('workflow.completed', { exact: false })).toBeVisible()
})

test('adds a task from a node plus connector', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.locator('.loop-node .node-add-connector').click()
  await expect(page.getByText('AGENTIC ORCHESTRATION')).toBeVisible()
  await page.locator('.quick-add-menu button').filter({ hasText: /^HTTP$/ }).click()
  await expect(page.locator('.quick-add-menu')).toHaveCount(0)
  await expect(page.locator('.canvas-ribbon')).toContainText('13 connections')
  await expect(page.locator('.task-node').filter({ hasText: 'http_task' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Add task inside Do While' }).click()
  await page.locator('.quick-add-menu button').filter({ hasText: /^HTTP$/ }).click()
  await expect(page.locator('.loop-node .group-slot')).toContainText('http_task')
  await page.getByRole('button', { name: 'Delete nested task http_task' }).click()
  await expect(page.locator('.loop-node .group-slot').filter({ hasText: 'http_task' })).toHaveCount(0)
})

test('deletes a task from its node close button', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  const task = page.locator('.task-node').filter({ hasText: 'http_task' })
  await expect(task).toHaveCount(1)
  await task.locator('.node-remove').click()
  await expect(task).toHaveCount(0)
})

test('configures a Worker Task from the Orkes task reference fields', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /Worker Task \(Simple\)/ }).first().click()
  await expect(page.getByText('Worker task options')).toBeVisible()
  await page.locator('input[placeholder="sayHello"]').fill('sayHello')
  await page.locator('.worker-section input[type="checkbox"]').nth(0).check()
  await expect(page.getByText('TTL (seconds)')).toBeVisible()
  await page.locator('.worker-section input[placeholder="${workflow.input.jobId}"]').fill('${workflow.input.firstName}')
  await page.locator('.worker-section input[type="checkbox"]').nth(1).check()
  await expect(page.getByText('Input schema')).toBeVisible()
})

test('shows the Orkes operator catalog in Add Task', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await expect(page.getByRole('button', { name: /Dynamic Fork/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Exclusive Join/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Get Workflow/ })).toBeVisible()
})

test('shows dedicated polling controls for an HTTP Poll task', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /HTTP Poll Task/ }).first().click()
  await expect(page.getByText('Polling', { exact: true })).toBeVisible()
  await expect(page.getByText('Poll interval (sec)', { exact: true })).toBeVisible()
  await expect(page.getByText('Poll condition', { exact: true })).toBeVisible()
})

test('shows dedicated official forms for advanced task types', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /Get Signed JWT/ }).first().click()
  await expect(page.getByText('Private key ID', { exact: true })).toBeVisible()
  await expect(page.getByText('Algorithm', { exact: true })).toBeVisible()
})

test('shows canonical fields for Kafka, gRPC, rules, databases and secrets', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /Kafka Publish/ }).first().click()
  await expect(page.getByText('Bootstrap server', { exact: true })).toBeVisible()
  await expect(page.getByText('Key serializer', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /gRPC Task/ }).first().click()
  await expect(page.getByText('Method type', { exact: true })).toBeVisible()
  await expect(page.getByText('Use SSL', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /Business Rule Task/ }).first().click()
  await expect(page.getByText('Rule file location', { exact: true })).toBeVisible()
  await expect(page.getByText('Input columns (JSON object)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /JDBC Task/ }).first().click()
  await expect(page.getByText('Statement type', { exact: true })).toBeVisible()
  await expect(page.getByText('Query parameters (JSON array)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /Update Secret/ }).first().click()
  await expect(page.getByText('Secret key', { exact: true })).toBeVisible()
  await expect(page.getByText('Secret value', { exact: true })).toBeVisible()
})

test('shows task-specific LLM and retrieval fields', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /LLM Chat Complete/ }).first().click()
  await expect(page.getByText('LLM provider', { exact: true })).toBeVisible()
  await expect(page.getByText('Messages (JSON array)', { exact: true })).toBeVisible()
  await expect(page.getByText('Max tokens', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /LLM Search Index/ }).first().click()
  await expect(page.getByText('Vector database', { exact: true })).toBeVisible()
  await expect(page.getByText('Query', { exact: true })).toBeVisible()
  await expect(page.getByText('Max results', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /Generate Video/ }).first().click()
  await expect(page.getByText('Input image (optional)', { exact: true })).toBeVisible()
  await expect(page.getByText('Generate thumbnail', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /Call MCP Tool/ }).first().click()
  await expect(page.getByText('MCP server URL', { exact: true })).toBeVisible()
  await expect(page.getByText('Arguments (JSON or variable reference)', { exact: true })).toBeVisible()
})

test('undo and redo restore task nodes together with their connections', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByTestId('rf__node-submit-job').click()
  await page.getByRole('button', { name: /Add another task/ }).click()
  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  await expect(page.locator('.canvas-ribbon')).toContainText('13 connections')
  const newTask = page.locator('.react-flow__node').filter({ hasText: 'http_task' }).first()
  await expect(newTask).toHaveCount(1)
  const pollLoop = page.getByTestId('rf__node-poll-loop')
  const yPosition = async (locator: typeof newTask) => (await locator.getAttribute('style'))?.match(/translate\([^,]+,\s*([^)]*)\)/)?.[1]
  expect(await yPosition(newTask)).toBe(await yPosition(pollLoop))

  await page.getByRole('button', { name: /Undo/ }).click()
  await expect(page.locator('.task-node').filter({ hasText: 'http_task' })).toHaveCount(0)
  await expect(page.locator('.canvas-ribbon')).toContainText('12 connections')

  await page.getByRole('button', { name: /Redo/ }).click()
  await expect(page.locator('.task-node').filter({ hasText: 'http_task' })).toHaveCount(1)
  await expect(page.locator('.canvas-ribbon')).toContainText('13 connections')
})

test('copies, pastes, and duplicates a node with a conflict-safe reference', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  const source = page.getByTestId('rf__node-submit-job')
  await source.click()
  await page.keyboard.press('Control+c')
  await page.keyboard.press('Control+v')
  await expect(page.locator('.task-node').filter({ hasText: 'submit_job_2' })).toHaveCount(1)

  await source.click({ button: 'right' })
  await expect(page.getByRole('button', { name: 'Copy node' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'View JSON' })).toBeVisible()
  await page.getByRole('button', { name: 'View JSON' }).click()
  await expect(page.getByRole('button', { name: 'Code', exact: true })).toHaveClass(/active/)
})

test('pauses, resumes, and terminates a running execution', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Execute', exact: true }).click()
  await page.getByRole('button', { name: 'Start execution', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible({ timeout: 2_000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflow is paused' })).toBeVisible()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Terminate', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Terminate', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Execution terminated' })).toBeVisible()
})

test('supports the workflow builder entry options from the definitions list', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/workflows')
  await expect(page.getByRole('heading', { name: 'Workflow Definitions' })).toBeVisible()
  await page.getByRole('button', { name: /New workflow/ }).click()
  await expect(page.getByText('Create blank', { exact: true })).toBeVisible()
  await expect(page.getByText('Use template', { exact: true })).toBeVisible()
  await expect(page.getByText('Import JSON', { exact: true })).toBeVisible()
  await expect(page.getByText('Generate with AI', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Create blank/ }).click()
  await expect(page.getByText('new_workflow', { exact: true })).toBeVisible()
  await expect(page.locator('.canvas-ribbon')).toContainText('0 tasks')
})

test('filters workflow definitions by lifecycle status', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/workflows')
  await page.getByLabel('Workflow status filter').selectOption('DRAFT')
  await expect(page.getByText('payment_and_subscription_flow', { exact: true })).toBeVisible()
  await expect(page.getByText('api_polling_workflow', { exact: true })).not.toBeVisible()
})

test('opens the global command palette with Ctrl+K', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
  await page.getByPlaceholder('Search commands...').fill('Queue monitor')
  await page.getByRole('button', { name: /Queue monitor/ }).click()
  await expect(page.getByRole('heading', { name: 'Queue Monitor', exact: true })).toBeVisible()
})

test('imports raw BPMN XML through the conversion review dialog', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Import BPMN', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Import BPMN', exact: true })).toBeVisible()
  await page.getByLabel('BPMN XML').fill('<definitions><process><startEvent id="start"/><userTask id="approve" name="Approve"/><subProcess id="loop" name="Poll" data-task-type="DO_WHILE"/><endEvent id="end"/><sequenceFlow id="a" sourceRef="start" targetRef="approve"/><sequenceFlow id="b" sourceRef="approve" targetRef="loop"/><sequenceFlow id="c" sourceRef="loop" targetRef="end"/></process></definitions>')
  await page.getByRole('button', { name: 'Review import', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Review imported workflow', exact: true })).toBeVisible()
  await expect(page.getByText('4', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Apply conversion', exact: true }).click()
  await expect(page.locator('.canvas-ribbon')).toContainText('2 tasks')
  await expect(page.getByText('Approve', { exact: true })).toBeVisible()
})

test('resizes and remembers the inspector panel width', async ({ page }) => {
  await page.addInitScript(() => { if (!window.sessionStorage.getItem('resize-test-started')) { window.localStorage.clear(); window.sessionStorage.setItem('resize-test-started', '1') } })
  await page.goto('/')
  const panel = page.locator('.panel-shell')
  const handle = page.locator('.panel-resize-handle')
  const initialWidth = await panel.evaluate((element) => element.getBoundingClientRect().width)
  const box = await handle.boundingBox()
  expect(box).not.toBeNull()
  if (!box) return
  await page.mouse.move(box.x + box.width / 2, box.y + 180)
  await page.mouse.down()
  await page.mouse.move(box.x - 70, box.y + 180)
  await page.mouse.up()
  const resizedWidth = await panel.evaluate((element) => element.getBoundingClientRect().width)
  expect(resizedWidth).toBeGreaterThan(initialWidth + 40)
  await page.reload()
  await expect.poll(() => panel.evaluate((element) => element.getBoundingClientRect().width)).toBe(resizedWidth)
})

test('navigates the supporting Conductor platform screens from the sidebar', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Queue Monitor', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Queue Monitor', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Event Monitor', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Event Monitor', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Task', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Task Definitions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Event Handler', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Event Handlers', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Scheduler', exact: true }).last().click()
  await expect(page.getByRole('heading', { name: 'Scheduler Definitions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Schemas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Schemas', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'APIs', exact: true }).click()
  await page.getByRole('button', { name: 'Services', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'API Reference', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Agents', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Agent Executions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Access Control' }).click()
  await page.getByRole('button', { name: 'Users', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Users', exact: true })).toBeVisible()
})

test('inspects polling workers from the queue monitor', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/queueMonitor')
  await page.getByRole('button', { name: /http_request/ }).click()
  await expect(page.getByText('Workers polling http_request', { exact: true })).toBeVisible()
  await expect(page.getByText('worker-http-01', { exact: true })).toBeVisible()
  await page.getByLabel('Auto refresh').selectOption('5')
  await expect(page.getByLabel('Auto refresh')).toHaveValue('5')
})

test('creates and filters reusable integrations', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/integrations')
  await page.getByRole('button', { name: 'New connection', exact: true }).click()
  await page.getByLabel('Connection name').fill('crm_api')
  await page.getByLabel('Connection category').selectOption('HTTP')
  await page.getByLabel('Connection endpoint').fill('https://crm.example.local')
  await page.getByRole('button', { name: 'Save connection', exact: true }).click()
  await expect(page.getByText('crm_api', { exact: true })).toBeVisible()
  await page.getByLabel('Integration category').selectOption('HTTP')
  await expect(page.getByText('crm_api', { exact: true })).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete integration crm_api', exact: true }).click()
  await expect(page.getByText('crm_api', { exact: true })).not.toBeVisible()
})

test('runs an agent with a prompt from the agent registry', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/agents')
  await page.getByRole('button', { name: 'Run agent news_research_agent', exact: true }).click()
  await page.getByLabel('Agent prompt').fill('Summarize the latest workflow failures.')
  await page.getByRole('button', { name: 'Run agent', exact: true }).click()
  await expect(page.getByText('Agent execution started:', { exact: false })).toBeVisible()
})

test('creates and removes task definitions and schedules', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/taskDefs')
  await page.getByRole('button', { name: 'New task definition', exact: true }).click()
  await page.getByLabel('Name').fill('email_worker')
  await page.getByLabel('Description').fill('Sends notification email')
  await page.getByLabel('Retry logic').selectOption('EXPONENTIAL_BACKOFF')
  await page.getByLabel('Backoff jitter (ms)').fill('250')
  await page.getByRole('button', { name: 'Save definition', exact: true }).click()
  await expect(page.getByText('email_worker', { exact: true })).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete task definition email_worker', exact: true }).click()
  await expect(page.getByText('email_worker', { exact: true })).not.toBeVisible()

  await page.getByRole('button', { name: 'Scheduler' }).last().click()
  await page.getByRole('button', { name: 'New schedule', exact: true }).click()
  await page.getByLabel('Name').fill('hourly_email')
  await page.getByLabel('Cron expression').fill('0 0 * * * *')
  await page.getByLabel('Catch up missed runs').check()
  await page.getByRole('button', { name: 'Save schedule', exact: true }).click()
  await expect(page.getByText('hourly_email', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Run schedule hourly_email', exact: true }).click()
  await expect(page.getByText('Schedule run started:', { exact: false })).toBeVisible()
})

test('replays an event into a workflow execution', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/eventMonitor')
  await page.getByRole('button', { name: /job\.completed/ }).click()
  await expect(page.getByRole('heading', { name: 'job.completed', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Replay event', exact: true }).click()
  await expect(page.getByText('Event replay started:', { exact: false })).toBeVisible()
})

test('sends a signal to an active execution', async ({ page }) => {
  await page.addInitScript(() => { if (!window.sessionStorage.getItem('signal-test-started')) { window.localStorage.clear(); window.sessionStorage.setItem('signal-test-started', '1') } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Execute', exact: true }).click()
  await page.getByRole('button', { name: 'Start execution', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflow is running', exact: true })).toBeVisible()
  await page.goto('/executions')
  await page.getByRole('button', { name: /api_polling_workflow/ }).first().click()
  await page.getByRole('button', { name: 'Send signal', exact: true }).click()
  await page.getByLabel('Signal name').fill('job.completed')
  await page.getByLabel('Payload (JSON)').fill('{"jobId":"job-42"}')
  await page.getByRole('button', { name: 'Send signal', exact: true }).last().click()
  await page.getByRole('button', { name: 'JSON', exact: true }).click()
  await expect(page.locator('.execution-json')).toContainText('job.completed')
})

test('persists platform registry resources and supports lifecycle actions', async ({ page }) => {
  await page.addInitScript(() => { if (!window.sessionStorage.getItem('registry-test-started')) { window.localStorage.clear(); window.sessionStorage.setItem('registry-test-started', '1') } })
  await page.goto('/agents')
  await page.getByRole('button', { name: 'New agent', exact: true }).click()
  await expect(page.getByText('new_agents_2', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('new_agents_2', { exact: true })).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete agent new_agents_2', exact: true }).click()
  await expect(page.getByText('new_agents_2', { exact: true })).not.toBeVisible()
})

test('edits workflow-level variables in the workflow inspector', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /HTTP Task/ }).first().click()
  await page.locator('.inspector-tabs').getByRole('button', { name: 'Workflow', exact: true }).click()
  await page.getByRole('button', { name: 'Schema and Parameters', exact: true }).click()
  await expect(page.getByText('Workflow variables', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add parameter', exact: true }).last().click()
  await page.getByLabel('Workflow variables key 2').fill('requestId')
  await page.getByLabel('Workflow variables value 2').fill('${workflow.input.requestId}')
  await expect(page.getByLabel('Workflow variables value 2')).toHaveValue('${workflow.input.requestId}')
})

test('persists schema drafts and validates selected schema content', async ({ page }) => {
  await page.addInitScript(() => { if (!window.sessionStorage.getItem('schema-test-started')) { window.localStorage.clear(); window.sessionStorage.setItem('schema-test-started', '1') } })
  await page.goto('/schemas')
  await page.getByRole('button', { name: 'New schema', exact: true }).click()
  await expect(page.getByRole('button', { name: /new_schema_3/ }).first()).toBeVisible()
  await page.locator('.schema-code-editor').fill('{')
  await page.getByRole('button', { name: 'Validate', exact: true }).click()
  await expect(page.locator('.schema-message.error')).toContainText('JSON')
  await page.locator('.schema-code-editor').fill('{"type":"object","properties":{"orderId":{"type":"string"}}}')
  await page.getByRole('button', { name: 'Validate', exact: true }).click()
  await expect(page.locator('.schema-message.success')).toContainText('1 properties')
  await page.reload()
  await expect(page.getByRole('button', { name: /new_schema_3/ }).first()).toBeVisible()
  await page.getByRole('button', { name: /new_schema_3/ }).first().click()
  await expect(page.locator('.schema-code-editor')).toHaveValue('{"type":"object","properties":{"orderId":{"type":"string"}}}')
})

test('runs a workflow from the platform Run Workflow screen', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/runWorkflow')
  await expect(page.getByRole('heading', { name: 'Run Workflow', exact: true })).toBeVisible()
  await page.getByLabel('Input params (JSON)').fill('{"source":"e2e"}')
  await page.getByLabel('Execution name').fill('platform-run-e2e')
  await page.getByRole('button', { name: 'Run workflow', exact: true }).click()
  await expect(page.getByText('Execution started', { exact: true })).toBeVisible()
  await expect(page.getByText('platform-run-e2e', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Workflow', exact: true }).first().click()
  await page.getByRole('button', { name: /platform-run-e2e/ }).click()
  await expect(page.getByRole('button', { name: 'Tasks', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Diagram', exact: true }).click()
  await expect(page.getByText('Execution diagram', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Summary', exact: true }).click()
  await expect(page.getByText('Reason for incompletion', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Input/Output', exact: true }).click()
  await expect(page.getByText('Workflow input', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'JSON', exact: true }).click()
  await expect(page.getByText('Execution JSON', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Tasks', exact: true }).click()
  await page.getByRole('button', { name: 'run_workflow_task_ref' }).click()
  await expect(page.getByRole('heading', { name: 'run_workflow_task_ref', exact: true })).toBeVisible()
  await page.getByLabel('Status').selectOption('FAILED')
  await page.getByLabel('Reason for incompletion').fill('Worker returned a terminal error')
  await page.getByRole('button', { name: 'Update task status', exact: true }).click()
  await expect(page.locator('.task-execution-modal')).toContainText('Worker returned a terminal error')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.locator('.execution-task-row').filter({ hasText: 'run_workflow_task_ref' })).toContainText('FAILED')
})

test('persists saved workflows and exposes definition list actions', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.goto('/workflows')
  await expect(page.getByText('api_polling_workflow', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Actions for api_polling_workflow', exact: true }).click()
  page.once('dialog', (dialog) => dialog.accept('api_polling_copy'))
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
  await expect(page.getByText('api_polling_copy', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Actions for api_polling_copy', exact: true }).click()
  await page.getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(page.locator('.workflow-row').filter({ hasText: 'api_polling_copy' })).toContainText('ARCHIVED')
})

test('deletes a saved workflow from the builder header', async ({ page }) => {
  await page.addInitScript(() => window.localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflow Definitions' })).toBeVisible()
  await expect(page.getByText('api_polling_workflow', { exact: true })).not.toBeVisible()
})
