import type { TaskKind } from '../workflowStore'

/** OSS task type registry aligned with the current conductor ui-next TaskType enum. */
export const OFFICIAL_TASK_KINDS = [
  'START', 'HTTP', 'SIMPLE', 'EVENT', 'GRPC', 'INLINE', 'JSON_JQ_TRANSFORM', 'BUSINESS_RULE', 'SQL',
  'AI_CHAT_COMPLETION', 'AI_GENERATE_IMAGE', 'DO_WHILE', 'SWITCH', 'TERMINATE', 'WAIT', 'HUMAN',
  'FORK_JOIN', 'FORK_JOIN_DYNAMIC', 'JOIN', 'DYNAMIC', 'SUB_WORKFLOW', 'START_WORKFLOW',
  'TERMINATE_WORKFLOW', 'YIELD', 'SET_VARIABLE', 'GET_WORKFLOW', 'EXCLUSIVE_JOIN', 'DECISION', 'USER_DEFINED', 'LAMBDA', 'TERMINAL',
  'KAFKA_PUBLISH', 'WAIT_FOR_EVENT', 'TASK_SUMMARY', 'SENDGRID', 'WAIT_FOR_WEBHOOK', 'HTTP_POLL', 'JDBC',
  'SWITCH_JOIN', 'IA_TASK', 'JUMP', 'LLM_TEXT_COMPLETE', 'LLM_GENERATE_EMBEDDINGS', 'LLM_GET_EMBEDDINGS',
  'LLM_STORE_EMBEDDINGS', 'LLM_SEARCH_INDEX', 'LLM_INDEX_DOCUMENT', 'GET_DOCUMENT', 'LLM_INDEX_TEXT',
  'UPDATE_SECRET', 'QUERY_PROCESSOR', 'OPS_GENIE', 'GET_SIGNED_JWT', 'UPDATE_TASK', 'LLM_CHAT_COMPLETE',
  'INTEGRATION', 'MCP_REMOTE', 'CHUNK_TEXT', 'LIST_FILES', 'PARSE_DOCUMENT', 'AGENT', 'GET_AGENT_CARD',
  'CANCEL_AGENT', 'LLM_SEARCH_EMBEDDINGS', 'LIST_MCP_TOOLS', 'CALL_MCP_TOOL', 'GENERATE_IMAGE',
  'GENERATE_AUDIO', 'GENERATE_VIDEO', 'GENERATE_PDF',
] as const satisfies readonly TaskKind[]

export function isOfficialTaskKind(value: string | null): value is TaskKind {
  return value != null && (OFFICIAL_TASK_KINDS as readonly string[]).includes(value)
}
