import { useEffect, useMemo, useState } from 'react'
import { Activity, Archive, Check, ChevronLeft, Clock3, Code2, Copy, FileJson, Filter, Globe2, Plus, RefreshCw, Search, Server, Settings2, UsersRound, Workflow, X } from 'lucide-react'
import { workflowApi, type EventHandlerRecord, type EventRecord, type ExecutionRecord, type QueueRecord, type ScheduleRecord, type TaskDefinitionRecord } from './workflowApi'

export type PlatformView = 'executions' | 'execution-detail' | 'queue' | 'events' | 'task-definitions' | 'event-handlers' | 'schedulers' | 'schemas' | 'api' | 'integrations' | 'access'

type Navigation = (view: PlatformView) => void

export function PlatformPage({ view, onNavigate }: { view: PlatformView; onNavigate: Navigation }) {
  if (view === 'executions' || view === 'execution-detail') return <ExecutionsPage />
  if (view === 'queue') return <QueueMonitorPage />
  if (view === 'events') return <EventMonitorPage />
  if (view === 'task-definitions') return <TaskDefinitionsPage />
  if (view === 'event-handlers') return <EventHandlersPage />
  if (view === 'schedulers') return <SchedulersPage />
  if (view === 'schemas') return <SchemasPage />
  if (view === 'api') return <ApiReferencePage />
  return <PlatformPlaceholder view={view} onNavigate={onNavigate} />
}

function PageFrame({ eyebrow, title, description, actions, children }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode; children: React.ReactNode }) {
  return <div className="platform-page"><header className="platform-page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="platform-page-actions">{actions}</div></header>{children}</div>
}

function Toolbar({ children }: { children: React.ReactNode }) { return <div className="platform-toolbar">{children}</div> }
function SearchBox({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="platform-search"><Search size={16} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label> }
function EmptyState({ icon: Icon = Workflow, title, detail }: { icon?: typeof Workflow; title: string; detail: string }) { return <div className="platform-empty"><Icon size={24} /><strong>{title}</strong><span>{detail}</span></div> }
function StatusPill({ value }: { value: string }) { return <em className={`platform-status ${value.toLowerCase().replaceAll('_', '-')}`}>{value.replaceAll('_', ' ')}</em> }
function formatTime(value?: string) { return value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—' }

function ExecutionsPage() {
  const [records, setRecords] = useState<ExecutionRecord[]>([])
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('ALL')
  const [selected, setSelected] = useState<ExecutionRecord | null>(null)
  const refresh = () => { void workflowApi.listExecutions().then(setRecords) }
  useEffect(() => { refresh() }, [])
  const visible = useMemo(() => records.filter((record) => `${record.executionId} ${record.workflowName} ${record.executionName ?? ''} ${record.correlationId ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'ALL' || record.status === status)), [query, records, status])
  if (selected) return <ExecutionDetail record={selected} onBack={() => { setSelected(null); refresh() }} />
  return <PageFrame eyebrow="EXECUTIONS / WORKFLOW" title="Workflow Executions" description="Search, inspect and operate workflow execution history." actions={<button className="outline-button" onClick={refresh}><RefreshCw size={15} /> Refresh</button>}>
    <Toolbar><SearchBox value={query} onChange={setQuery} placeholder="Search execution, workflow or correlation ID..." /><label className="platform-select"><Filter size={15} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option><option>RUNNING</option><option>PAUSED</option><option>COMPLETED</option><option>TERMINATED</option><option>FAILED</option></select></label></Toolbar>
    <div className="platform-card"><div className="platform-card-head"><div><strong>Recent executions</strong><span>{visible.length} result{visible.length === 1 ? '' : 's'}</span></div><div className="platform-card-metrics"><span><b>{records.filter((item) => item.status === 'RUNNING').length}</b> running</span><span><b>{records.filter((item) => item.status === 'COMPLETED').length}</b> completed</span></div></div>{visible.length === 0 ? <EmptyState icon={Activity} title="No executions found" detail="Run a workflow from the builder to populate this list." /> : <div className="platform-table"><div className="platform-table-head"><span>Execution</span><span>Workflow</span><span>Status</span><span>Started</span><span>Tasks</span><span /></div>{visible.map((record) => <button className="platform-table-row" key={record.executionId} onClick={() => setSelected(record)}><span><strong>{record.executionName || record.executionId}</strong><small>{record.executionId}</small></span><span>{record.workflowName}<small>Version {record.version}</small></span><span><StatusPill value={record.status} /></span><span>{formatTime(record.startedAt)}</span><span>{record.events.filter((event) => event.status === 'COMPLETED').length}/{record.events.length || '—'}</span><ChevronLeft className="rotate-180" size={15} /></button>)}</div>}</div>
  </PageFrame>
}

function ExecutionDetail({ record, onBack }: { record: ExecutionRecord; onBack: () => void }) {
  return <PageFrame eyebrow="EXECUTIONS / DETAIL" title={record.executionName || record.executionId} description={`${record.workflowName} · version ${record.version}`} actions={<button className="outline-button" onClick={onBack}><ChevronLeft size={15} /> Back to executions</button>}>
    <div className="detail-grid"><div className="platform-card"><div className="platform-card-head"><div><strong>Execution summary</strong><span>{record.executionId}</span></div><StatusPill value={record.status} /></div><div className="metric-grid"><div><span>Started</span><strong>{formatTime(record.startedAt)}</strong></div><div><span>Completed</span><strong>{formatTime(record.completedAt)}</strong></div><div><span>Correlation ID</span><strong>{record.correlationId || '—'}</strong></div><div><span>Priority</span><strong>{record.priority ?? 0}</strong></div></div></div><div className="platform-card"><div className="platform-card-head"><div><strong>Execution input</strong><span>JSON payload</span></div><Code2 size={17} /></div><pre className="platform-code">{JSON.stringify(record.input, null, 2)}</pre></div></div>
    <div className="platform-card"><div className="platform-card-head"><div><strong>Task timeline</strong><span>{record.events.length} task events</span></div></div>{record.events.length === 0 ? <EmptyState icon={Clock3} title="No task events yet" detail="This execution has not emitted task events." /> : <div className="execution-task-table">{record.events.map((event, index) => <div className="execution-task-row" key={`${event.taskReferenceName}-${index}`}><span className="timeline-dot" /><div><strong>{event.taskReferenceName}</strong><small>{formatTime(event.at)}{event.workerId ? ` · ${event.workerId}` : ''}</small></div><StatusPill value={event.status} /><span className="task-reason">{event.reasonForIncompletion || ''}</span></div>)}</div>}</div>
  </PageFrame>
}

function QueueMonitorPage() {
  const [queues, setQueues] = useState<QueueRecord[]>([])
  const [query, setQuery] = useState('')
  const refresh = () => { void workflowApi.listQueues().then(setQueues) }
  useEffect(() => { refresh() }, [])
  const visible = queues.filter((queue) => `${queue.queue} ${queue.taskType}`.toLowerCase().includes(query.toLowerCase()))
  const inProgress = queues.reduce((sum, queue) => sum + queue.inProgress, 0)
  const unprocessed = queues.reduce((sum, queue) => sum + queue.unprocessed, 0)
  return <PageFrame eyebrow="EXECUTIONS / QUEUE MONITOR" title="Queue Monitor" description="Inspect worker queues, throughput and pending work." actions={<button className="outline-button" onClick={refresh}><RefreshCw size={15} /> Refresh</button>}><div className="metric-cards"><MetricCard icon={Activity} label="In progress" value={inProgress} tone="blue" /><MetricCard icon={Clock3} label="Unprocessed" value={unprocessed} tone="amber" /><MetricCard icon={Server} label="Active queues" value={queues.length} tone="green" /></div><Toolbar><SearchBox value={query} onChange={setQuery} placeholder="Search queues..." /></Toolbar><div className="platform-card"><div className="platform-table"><div className="platform-table-head"><span>Queue</span><span>Task type</span><span>In progress</span><span>Unprocessed</span><span>Rate limit</span><span>Updated</span></div>{visible.map((queue) => <div className="platform-table-row static" key={queue.queue}><span><strong>{queue.queue}</strong></span><span>{queue.taskType}</span><span>{queue.inProgress}</span><span className={queue.unprocessed ? 'warning-text' : ''}>{queue.unprocessed}</span><span>{queue.rateLimit}/min</span><span>{queue.updatedAt}</span></div>)}</div></div></PageFrame>
}

function MetricCard({ icon: Icon, label, value, tone }: { icon: typeof Activity; label: string; value: number; tone: string }) { return <div className={`metric-card ${tone}`}><Icon size={18} /><span>{label}</span><strong>{value}</strong></div> }

function EventMonitorPage() {
  const [events, setEvents] = useState<EventRecord[]>([])
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<EventRecord | null>(null)
  useEffect(() => { void workflowApi.listEvents().then(setEvents) }, [])
  const visible = events.filter((event) => `${event.event} ${event.source} ${event.id} ${event.status}`.toLowerCase().includes(query.toLowerCase()))
  return <PageFrame eyebrow="EXECUTIONS / EVENT MONITOR" title="Event Monitor" description="Track incoming events and inspect their processing status." actions={<button className="outline-button" onClick={() => void workflowApi.listEvents().then(setEvents)}><RefreshCw size={15} /> Refresh</button>}><Toolbar><SearchBox value={query} onChange={setQuery} placeholder="Search event name, source or ID..." /></Toolbar><div className="platform-card"><div className="platform-table"><div className="platform-table-head"><span>Event</span><span>Source</span><span>Status</span><span>Received</span><span>ID</span><span /></div>{visible.map((event) => <button className="platform-table-row" key={event.id} onClick={() => setSelected(event)}><span><strong>{event.event}</strong></span><span>{event.source}</span><span><StatusPill value={event.status} /></span><span>{event.receivedAt}</span><span>{event.id}</span><ChevronLeft className="rotate-180" size={15} /></button>)}</div></div>{selected && <div className="modal-backdrop"><section className="platform-modal"><div className="modal-head"><div><span className="eyebrow">EVENT DETAIL</span><h2>{selected.event}</h2><p>{selected.id} · {selected.source}</p></div><button onClick={() => setSelected(null)}><X size={17} /></button></div><div className="modal-event-meta"><StatusPill value={selected.status} /><span>Received {selected.receivedAt}</span></div><pre className="platform-code">{JSON.stringify(selected.payload, null, 2)}</pre></section></div>}</PageFrame>
}

function TaskDefinitionsPage() {
  const [items, setItems] = useState<TaskDefinitionRecord[]>([])
  const [query, setQuery] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [draft, setDraft] = useState<TaskDefinitionDraft>({ name: '', description: '', owner: 'platform', timeoutSeconds: '60', retryCount: '3' })
  const refresh = () => { void workflowApi.listTaskDefinitions().then(setItems) }
  useEffect(() => { refresh() }, [])
  const visible = items.filter((item) => `${item.name} ${item.description} ${item.owner}`.toLowerCase().includes(query.toLowerCase()))
  const save = () => { if (!draft.name.trim()) return; void workflowApi.saveTaskDefinition({ name: draft.name.trim(), description: draft.description, owner: draft.owner, timeoutSeconds: Number(draft.timeoutSeconds) || 60, retryCount: Number(draft.retryCount) || 0, updatedAt: new Date().toISOString(), status: 'ACTIVE' }).then(() => { setFormOpen(false); setDraft({ name: '', description: '', owner: 'platform', timeoutSeconds: '60', retryCount: '3' }); refresh() }) }
  return <PageFrame eyebrow="DEFINITIONS / TASK" title="Task Definitions" description="Manage worker task contracts, retry policy and execution timeouts." actions={<button className="primary-action" onClick={() => setFormOpen(true)}><Plus size={15} /> New task definition</button>}><Toolbar><SearchBox value={query} onChange={setQuery} placeholder="Search task definitions..." /><span className="toolbar-count">{visible.length} definitions</span></Toolbar><div className="platform-card"><div className="platform-table"><div className="platform-table-head"><span>Task definition</span><span>Owner</span><span>Timeout</span><span>Retries</span><span>Status</span><span>Updated</span></div>{visible.map((item) => <div className="platform-table-row static" key={item.name}><span><strong>{item.name}</strong><small>{item.description}</small></span><span>{item.owner}</span><span>{item.timeoutSeconds}s</span><span>{item.retryCount}</span><span><StatusPill value={item.status} /></span><span>{item.updatedAt}</span></div>)}</div></div>{formOpen && <TaskDefinitionModal draft={draft} setDraft={setDraft} onCancel={() => setFormOpen(false)} onSave={save} />}</PageFrame>
}

type TaskDefinitionDraft = { name: string; description: string; owner: string; timeoutSeconds: string; retryCount: string }

function TaskDefinitionModal({ draft, setDraft, onCancel, onSave }: { draft: TaskDefinitionDraft; setDraft: (draft: TaskDefinitionDraft) => void; onCancel: () => void; onSave: () => void }) { return <div className="modal-backdrop"><section className="platform-modal"><div className="modal-head"><div><span className="eyebrow">TASK DEFINITIONS</span><h2>New task definition</h2><p>Register the contract used by worker tasks.</p></div><button onClick={onCancel}><X size={17} /></button></div><div className="modal-fields"><label>Name<input value={draft.name} placeholder="send_email" onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Description<input value={draft.description} placeholder="Sends a transactional email" onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><div className="compact-fields"><label>Owner<input value={draft.owner} onChange={(event) => setDraft({ ...draft, owner: event.target.value })} /></label><label>Timeout (sec)<input type="number" value={draft.timeoutSeconds} onChange={(event) => setDraft({ ...draft, timeoutSeconds: event.target.value })} /></label><label>Retry count<input type="number" value={draft.retryCount} onChange={(event) => setDraft({ ...draft, retryCount: event.target.value })} /></label></div></div><div className="modal-actions"><button className="outline-button" onClick={onCancel}>Cancel</button><button className="primary-action" onClick={onSave}><Check size={14} /> Save definition</button></div></section></div> }

function EventHandlersPage() {
  const [items, setItems] = useState<EventHandlerRecord[]>([])
  const [formOpen, setFormOpen] = useState(false)
  const [draft, setDraft] = useState({ name: '', event: '', action: 'START_WORKFLOW', workflowName: 'api_polling_workflow' })
  const refresh = () => { void workflowApi.listEventHandlers().then(setItems) }
  useEffect(() => { refresh() }, [])
  const save = () => { if (!draft.name.trim() || !draft.event.trim()) return; void workflowApi.saveEventHandler({ ...draft, name: draft.name.trim(), event: draft.event.trim(), active: true, updatedAt: new Date().toISOString() }).then(() => { setFormOpen(false); refresh() }) }
  return <PageFrame eyebrow="DEFINITIONS / EVENT HANDLER" title="Event Handlers" description="Route incoming events to workflows and platform actions." actions={<button className="primary-action" onClick={() => setFormOpen(true)}><Plus size={15} /> New event handler</button>}><div className="platform-card"><div className="platform-table"><div className="platform-table-head"><span>Handler</span><span>Event</span><span>Action</span><span>Workflow</span><span>Status</span><span>Updated</span></div>{items.map((item) => <div className="platform-table-row static" key={item.name}><span><strong>{item.name}</strong></span><span>{item.event}</span><span>{item.action}</span><span>{item.workflowName}</span><span><StatusPill value={item.active ? 'ACTIVE' : 'PAUSED'} /></span><span>{item.updatedAt}</span></div>)}</div></div>{formOpen && <div className="modal-backdrop"><section className="platform-modal"><div className="modal-head"><div><span className="eyebrow">EVENT HANDLERS</span><h2>New event handler</h2></div><button onClick={() => setFormOpen(false)}><X size={17} /></button></div><div className="modal-fields"><label>Name<input value={draft.name} placeholder="order_completed" onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Event name<input value={draft.event} placeholder="order.completed" onChange={(event) => setDraft({ ...draft, event: event.target.value })} /></label><div className="compact-fields"><label>Action<select className="native-select" value={draft.action} onChange={(event) => setDraft({ ...draft, action: event.target.value })}><option>START_WORKFLOW</option><option>PUBLISH_EVENT</option><option>UPDATE_SECRET</option></select></label><label>Workflow<input value={draft.workflowName} onChange={(event) => setDraft({ ...draft, workflowName: event.target.value })} /></label></div></div><div className="modal-actions"><button className="outline-button" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary-action" onClick={save}><Check size={14} /> Save handler</button></div></section></div>}</PageFrame>
}

function SchedulersPage() {
  const [items, setItems] = useState<ScheduleRecord[]>([])
  const [formOpen, setFormOpen] = useState(false)
  const [draft, setDraft] = useState({ name: '', workflowName: 'api_polling_workflow', cronExpression: '0 */5 * * * *', timezone: 'UTC' })
  const refresh = () => { void workflowApi.listSchedules().then(setItems) }
  useEffect(() => { refresh() }, [])
  const save = () => { if (!draft.name.trim()) return; void workflowApi.saveSchedule({ ...draft, name: draft.name.trim(), active: true, nextRun: 'Calculating…', updatedAt: new Date().toISOString() }).then(() => { setFormOpen(false); refresh() }) }
  const toggle = (item: ScheduleRecord) => { void workflowApi.saveSchedule({ ...item, active: !item.active, nextRun: item.active ? 'Paused' : 'Calculating…', updatedAt: new Date().toISOString() }).then(refresh) }
  return <PageFrame eyebrow="DEFINITIONS / SCHEDULER" title="Scheduler Definitions" description="Create and operate cron-based workflow schedules." actions={<button className="primary-action" onClick={() => setFormOpen(true)}><Plus size={15} /> New schedule</button>}><div className="platform-card"><div className="platform-table"><div className="platform-table-head"><span>Schedule</span><span>Workflow</span><span>Cron</span><span>Timezone</span><span>Status</span><span>Next run</span></div>{items.map((item) => <div className="platform-table-row static" key={item.name}><span><strong>{item.name}</strong></span><span>{item.workflowName}</span><span><code>{item.cronExpression}</code></span><span>{item.timezone}</span><button className="inline-status-button" onClick={() => toggle(item)}><StatusPill value={item.active ? 'ACTIVE' : 'PAUSED'} /></button><span>{item.nextRun}</span></div>)}</div></div>{formOpen && <div className="modal-backdrop"><section className="platform-modal"><div className="modal-head"><div><span className="eyebrow">SCHEDULER</span><h2>New schedule</h2></div><button onClick={() => setFormOpen(false)}><X size={17} /></button></div><div className="modal-fields"><label>Name<input value={draft.name} placeholder="nightly_cleanup" onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Workflow<input value={draft.workflowName} onChange={(event) => setDraft({ ...draft, workflowName: event.target.value })} /></label><div className="compact-fields"><label>Cron expression<input value={draft.cronExpression} onChange={(event) => setDraft({ ...draft, cronExpression: event.target.value })} /></label><label>Timezone<input value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} /></label></div></div><div className="modal-actions"><button className="outline-button" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary-action" onClick={save}><Check size={14} /> Save schedule</button></div></section></div>}</PageFrame>
}

function SchemasPage() {
  const [schemas, setSchemas] = useState([{ name: 'workflow_input_v1', version: 1, format: 'JSON', status: 'ACTIVE', fields: 4 }, { name: 'worker_output_v1', version: 2, format: 'JSON', status: 'ACTIVE', fields: 8 }])
  const [selected, setSelected] = useState(schemas[0])
  const [schemaText, setSchemaText] = useState('{\n  "type": "object",\n  "properties": {\n    "jobId": { "type": "string" }\n  }\n}')
  const [query, setQuery] = useState('')
  const visible = schemas.filter((schema) => schema.name.toLowerCase().includes(query.toLowerCase()))
  return <PageFrame eyebrow="DEFINITIONS / SCHEMAS" title="Schemas" description="Version and validate JSON schemas used by workflows and worker tasks." actions={<button className="primary-action" onClick={() => { const name = `new_schema_${schemas.length + 1}`; const next = { name, version: 1, format: 'JSON', status: 'DRAFT', fields: 0 }; setSchemas([...schemas, next]); setSelected(next) }}><Plus size={15} /> New schema</button>}><div className="schema-layout"><div className="platform-card schema-list"><Toolbar><SearchBox value={query} onChange={setQuery} placeholder="Search schemas..." /></Toolbar>{visible.map((schema) => <button className={`schema-list-item ${selected.name === schema.name ? 'active' : ''}`} key={schema.name} onClick={() => setSelected(schema)}><FileJson size={16} /><span><strong>{schema.name}</strong><small>v{schema.version} · {schema.fields} fields</small></span><StatusPill value={schema.status} /></button>)}</div><div className="platform-card schema-editor"><div className="platform-card-head"><div><strong>{selected.name}</strong><span>Version {selected.version} · {selected.format}</span></div><button className="outline-button compact-button" onClick={() => { try { JSON.parse(schemaText); setSchemas(schemas.map((item) => item.name === selected.name ? { ...item, status: 'ACTIVE', fields: Math.max(1, Object.keys(JSON.parse(schemaText).properties ?? {}).length) } : item)) } catch { /* editor keeps invalid JSON visible for correction */ } }}><Check size={14} /> Validate</button></div><textarea className="schema-code-editor" value={schemaText} onChange={(event) => setSchemaText(event.target.value)} spellCheck={false} /><div className="schema-editor-footer"><span>JSON Schema draft 2020-12</span><button className="primary-action" onClick={() => setSchemas(schemas.map((item) => item.name === selected.name ? { ...item, version: item.version + 1 } : item))}><Archive size={14} /> Publish version</button></div></div></div></PageFrame>
}

function ApiReferencePage() {
  const endpoints = [{ group: 'Workflow', method: 'GET', path: '/api/workflow/{name}', desc: 'Get a workflow definition.' }, { group: 'Workflow', method: 'POST', path: '/api/workflow', desc: 'Create or update a workflow definition.' }, { group: 'Execution', method: 'POST', path: '/api/workflow/{name}/execute', desc: 'Start a workflow execution.' }, { group: 'Execution', method: 'GET', path: '/api/workflow/{name}/{id}', desc: 'Get execution details.' }, { group: 'Task', method: 'GET', path: '/api/tasks/queue/{taskType}', desc: 'Inspect a task queue.' }, { group: 'Event', method: 'POST', path: '/api/event', desc: 'Publish an event.' }]
  const [query, setQuery] = useState('')
  const visible = endpoints.filter((endpoint) => `${endpoint.group} ${endpoint.method} ${endpoint.path} ${endpoint.desc}`.toLowerCase().includes(query.toLowerCase()))
  return <PageFrame eyebrow="API DOCS" title="API Reference" description="Explore the Conductor-compatible APIs exposed by this workspace." actions={<button className="outline-button" onClick={() => navigator.clipboard?.writeText('http://localhost:8080/api')}><Copy size={15} /> Copy base URL</button>}><Toolbar><SearchBox value={query} onChange={setQuery} placeholder="Search API operations..." /></Toolbar><div className="api-reference-list">{visible.map((endpoint) => <div className="api-operation" key={`${endpoint.method}-${endpoint.path}`}><div className={`api-method ${endpoint.method.toLowerCase()}`}>{endpoint.method}</div><div><strong>{endpoint.path}</strong><span>{endpoint.group} · {endpoint.desc}</span></div><button className="icon-button" aria-label={`Copy ${endpoint.path}`} onClick={() => navigator.clipboard?.writeText(endpoint.path)}><Copy size={15} /></button><ChevronLeft className="rotate-180" size={15} /></div>)}</div></PageFrame>
}

function PlatformPlaceholder({ view, onNavigate }: { view: PlatformView; onNavigate: Navigation }) {
  const title = view === 'integrations' ? 'Integrations' : 'Access Control'
  const Icon = view === 'integrations' ? Globe2 : UsersRound
  return <PageFrame eyebrow={view === 'integrations' ? 'INTEGRATIONS' : 'ACCESS CONTROL'} title={title} description={view === 'integrations' ? 'Manage connected applications and service resources.' : 'Manage applications, groups and user permissions.'}><div className="placeholder-grid"><div className="platform-card placeholder-card"><Icon size={24} /><strong>{view === 'integrations' ? 'Connections and resources' : 'Applications and groups'}</strong><span>This local workspace provides the navigation surface and state model for the platform module.</span><button className="outline-button" onClick={() => onNavigate(view === 'integrations' ? 'api' : 'task-definitions')}>{view === 'integrations' ? 'View API resources' : 'Review task access'} <ChevronLeft className="rotate-180" size={14} /></button></div><div className="platform-card placeholder-card"><Settings2 size={24} /><strong>Workspace settings</strong><span>Configure environment-level settings when a connected Conductor backend is available.</span></div></div></PageFrame>
}
